sudo: required
services:
  - docker

before_install:
  - docker build -t fongchinghinstephen/react-test -f ./react-server/Dockerfile.dev ./react-server

scripts:
  - docker run -e CI=true fongchinghinstephen/react-test npm test

after_success:
  - docker build -t fongchinghinstephen/react-server ./react-server
  - docker build -t fongchinghinstephen/express-server ./express-server
  - docker build -t fongchinghinstephen/nginx ./nginx
  - docker build -t fongchinghinstephen/worker ./worker
  # login to the CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push fongchinghinstephen/react-server
  - docker push fongchinghinstephen/express-server
  - docker push fongchinghinstephen/nginx
  - docker push fongchinghinstephen/worker
